version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=oneapi
      - MYSQL_USER=oneapi
      - MYSQL_PASSWORD=admin123
      - TZ=Asia/Shanghai
    volumes:
      - /opt/mysql:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

